# Generated by Django 3.1.7 on 2021-03-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description',
            field=models.TextField(default='testtest'),
            preserve_default=False,
        ),
    ]
