# Generated by Django 3.1.7 on 2021-03-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_aboutme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(default=0, upload_to='aboutyou/images/'),
            preserve_default=False,
        ),
    ]
