# Generated by Django 3.1.7 on 2021-03-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_aboutme_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
    ]
