# Generated by Django 3.1.7 on 2021-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutyou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutyou',
            name='image',
            field=models.ImageField(default=0, upload_to='aboutyou/images/'),
            preserve_default=False,
        ),
    ]
