# Generated by Django 3.1.7 on 2021-03-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='characters',
            new_name='description',
        ),
    ]
